coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "test/**/*"
  - "script/**/*"
  - "lib/**/*"

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
