coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "src/**/*"
    patch:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "src/**/*"

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
